esphome:
  name: dtu-open
  friendly_name: dtu-open

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "E/Zl2vP6MPxYD4bD0sZdVj0XwjNXS0on7dqL292nUes="

ota:
  password: "ca47b7b176c6d245abee11a3be5ddf29"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dtu-Open Fallback Hotspot"
    password: !secret wifi_password
  
sensor:
  - platform: pulse_counter
    pin: 12
    unit_of_measurement: 'kW'
    name: "Solar"
    total:
      unit_of_measurement: 'kWh'
      name: 'Solar Sum'
      filters:
        - multiply: 0.0005  # (1/2000 pulses per kWh)
#tck = 13   
  - platform: pulse_counter
    pin: 14
    unit_of_measurement: 'kW'
    name: "Climate"
    total:
      unit_of_measurement: 'kWh'
      name: 'Climate Sum'
      filters:
        - multiply: 0.0005  # (1/2000 pulses per kWh)

        

captive_portal:
    
